  # Spring properties
spring:
    application:
        name: product-service  # Service registers under this name
    datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        password:
        initialization-mode: always
        data: classpath:/init_data.sql
        jpa:
            properties:
                hibernate:
                    dialect: org.hibernate.dialect.H2Dialect
    h2:
        console:
            enabled: true
            path: /h2-console

# HTTP Server
server:
    port: 1236   # HTTP (Tomcat) port

# Discovery Server Access
# Define URL of registration server (defaultZone)
eureka:
    instance:
        leaseRenewalIntervalInSeconds: 5
        instance-id: ${spring.application.name}
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:1234/eureka/

