  # Spring properties
spring:
    application:
        name: search-service  # Service registers under this name
    datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        password:
        initialization-mode: always
        data: classpath:/init_data.sql
        jpa:
            properties:
                hibernate:
                    dialect: org.hibernate.dialect.H2Dialect
    h2:
        console:
            enabled: true
            path: /h2-console

# Map the error path to error template (for Thymeleaf)
error.path: /error

# HTTP Server
server.port: 1235   # HTTP (Tomcat) port

# Discovery Server Access
# Define URL of registration server (defaultZone)
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1234/eureka/
